// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubjectOrderDetails.DbContexts;

namespace SubjectOrderDetails.Migrations
{
    [DbContext(typeof(SubjectOrderContext))]
    [Migration("20201016122523_MoreSubjectsandSchemaChanges")]
    partial class MoreSubjectsandSchemaChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SubjectOrderDetails.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.HasIndex("TitleId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            DateOfBirth = new DateTimeOffset(new DateTime(1976, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            FirstName = "Daniel",
                            LastName = "Garsden",
                            TitleId = 1
                        },
                        new
                        {
                            SubjectId = 2,
                            DateOfBirth = new DateTimeOffset(new DateTime(2015, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Tamas",
                            LastName = "Garsden",
                            TitleId = 3
                        },
                        new
                        {
                            SubjectId = 3,
                            DateOfBirth = new DateTimeOffset(new DateTime(2017, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Alma",
                            LastName = "Garsden",
                            TitleId = 4
                        },
                        new
                        {
                            SubjectId = 4,
                            DateOfBirth = new DateTimeOffset(new DateTime(1949, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            FirstName = "Phillip",
                            LastName = "Garsden",
                            TitleId = 4
                        },
                        new
                        {
                            SubjectId = 5,
                            DateOfBirth = new DateTimeOffset(new DateTime(1986, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            FirstName = "Jennifer",
                            LastName = "Garsden",
                            TitleId = 4
                        });
                });

            modelBuilder.Entity("SubjectOrderDetails.Entities.Title", b =>
                {
                    b.Property<int>("titleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("titleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("titleId");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            titleId = 1,
                            titleName = "Mr"
                        },
                        new
                        {
                            titleId = 2,
                            titleName = "Mrs"
                        },
                        new
                        {
                            titleId = 3,
                            titleName = "Master"
                        },
                        new
                        {
                            titleId = 4,
                            titleName = "Miss"
                        });
                });

            modelBuilder.Entity("SubjectOrderDetails.Entities.Subject", b =>
                {
                    b.HasOne("SubjectOrderDetails.Entities.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
